import Link from "next/link"
import "./globals.css"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>{children}</body>
      <Link href={'/about'}><button className="btn-secondary btn">About</button></Link>
    </html>
  )
}
